import CoffeeLogo from "../assets/icons/CoffeeLogo.svg";
import Banner from "../assets/images/banner.png";
import Search from "../assets/icons/search.svg";
import Message from "../assets/icons/msg.svg";
import ProfileNav from "../assets/icons/ProfileNav.svg";
import ProductImg from "../assets/images/product-right.png";
import Google from "../assets/icons/google.svg";
import ProductCold from "../assets/images/cold-brew.png";
import Teamwork from "../assets/images/teamwork.png";
import BackgroundChat from "../assets/images/bgchats.png";
import DefaultPic from "../assets/images/Default_pic.svg";
import Card from "../assets/icons/card.png";
import Bank from "../assets/icons/Bank.png";
import Cod from "../assets/icons/Cod.png";
import ProductCoupon from "../assets/images/product-coupon.png";
import EmptyCart from "../assets/icons/empty-cart.png";
export { CoffeeLogo, Banner, Search, Message, ProfileNav, ProductImg, Google, ProductCold, Teamwork, BackgroundChat, DefaultPic, Card, Bank, Cod, ProductCoupon, EmptyCart };